# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 00:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_api', '0002_auto_20160207_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Game State')),
                ('game_time', models.FloatField(default=0.0, verbose_name='Game Time in Seconds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('seed', models.CharField(max_length=50, verbose_name='Random Seed')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.Game')),
                ('initial_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.Snapshot')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
            },
        ),
        migrations.CreateModel(
            name='SpaceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spacesettingss', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Space Settings',
                'verbose_name_plural': 'Space Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='gamesettings',
            options={'verbose_name': 'Game Settings', 'verbose_name_plural': 'Game Settings'},
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamesettingss', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='space',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.SpaceSettings'),
        ),
    ]
