# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_auto_20160207_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomSnapshot',
            fields=[
                ('snapshot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_api.Snapshot')),
            ],
            options={
                'abstract': False,
            },
            bases=('game_api.snapshot',),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.Game'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.SpaceSettings'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.Space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='initial_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game_api.Snapshot'),
        ),
    ]
