# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0004_auto_20160213_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultGameSettings',
            fields=[
                ('gamesettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_api.GameSettings')),
            ],
            options={
                'verbose_name': 'Default Game Settings',
                'verbose_name_plural': 'Default Game Settings',
            },
            bases=('game_api.gamesettings',),
        ),
        migrations.CreateModel(
            name='DefaultSpaceSettings',
            fields=[
                ('gamesettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_api.GameSettings')),
            ],
            options={
                'verbose_name': 'Default Space Settings',
                'verbose_name_plural': 'Default Space Settings',
            },
            bases=('game_api.gamesettings',),
        ),
    ]
