# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0006_auto_20160214_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSpaceSettings',
            fields=[
                ('spacesettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_api.SpaceSettings')),
            ],
            options={
                'verbose_name_plural': 'Default Space Settings',
                'verbose_name': 'Default Space Settings',
            },
            bases=('game_api.spacesettings',),
        ),
    ]
